[package]
name = "plotters-backend"
version = "0.0.0-dummy"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
